import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import {
  CreateCustomerInput,
  useCreateCustomerMutation,
} from "./api/generated";

const Home: NextPage = () => {
  const [createCustomer, { data, loading, error }] =
    useCreateCustomerMutation();

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const renderSignUpForm = () => {
    return (
      <form>
        <input
          id="name"
          type="text"
          name="name"
          onChange={(e) => setName(e.target.value)}
        />
        <input
          id="email"
          type="text"
          name="email"
          onChange={(e) => setEmail(e.target.value)}
        />
        <input
          id="password"
          type="text"
          name="password"
          onChange={(e) => setPassword(e.target.value)}
        />
        <button
          type="submit"
          disabled={
            name.length === 0 || email.length === 0 || password.length === 0
          }
          onClick={async (e) => {
            e.preventDefault();
            const input: CreateCustomerInput = {
              name,
              email,
              password,
            };
            await createCustomer({ variables: { input } });
            console.log(1);
            // .then((customer) => console.log("customer", customer))
            // .catch((error) => console.error(error));
          }}
        >
          Sign Up
        </button>
      </form>
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {renderSignUpForm()}
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
